[2025-03-30 22:20:43,593] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.upload_state_lookup manual__2025-03-30T22:20:34.074488+00:00 [queued]>
[2025-03-30 22:20:43,617] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.upload_state_lookup manual__2025-03-30T22:20:34.074488+00:00 [queued]>
[2025-03-30 22:20:43,618] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:20:43,618] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 22:20:43,618] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:20:43,637] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): upload_state_lookup> on 2025-03-30 22:20:34.074488+00:00
[2025-03-30 22:20:43,647] {standard_task_runner.py:52} INFO - Started process 319 to run task
[2025-03-30 22:20:43,654] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'upload_state_lookup', 'manual__2025-03-30T22:20:34.074488+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmpisu1dq7k', '--error-file', '/tmp/tmplebi5gkf']
[2025-03-30 22:20:43,659] {standard_task_runner.py:77} INFO - Job 87: Subtask upload_state_lookup
[2025-03-30 22:20:43,757] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.upload_state_lookup manual__2025-03-30T22:20:34.074488+00:00 [running]> on host 6e74f7e5ce4c
[2025-03-30 22:20:43,850] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=upload_state_lookup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T22:20:34.074488+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T22:20:34.074488+00:00
[2025-03-30 22:20:43,857] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-30 22:20:43,867] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 59, in upload_local_file_to_gcs
    gcs_hook.upload(GCP_GCS_BUCKET, gcs_path, output_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 481, in upload
    partial(blob.upload_from_filename, filename=filename, content_type=mime_type, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 442, in _call_with_retry
    f()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'state_lookup.csv'
[2025-03-30 22:20:43,891] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=natality_web_data_to_gcs, task_id=upload_state_lookup, execution_date=20250330T222034, start_date=20250330T222043, end_date=20250330T222043
[2025-03-30 22:20:43,922] {standard_task_runner.py:92} ERROR - Failed to execute job 87 for task upload_state_lookup
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 59, in upload_local_file_to_gcs
    gcs_hook.upload(GCP_GCS_BUCKET, gcs_path, output_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 481, in upload
    partial(blob.upload_from_filename, filename=filename, content_type=mime_type, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 442, in _call_with_retry
    f()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'state_lookup.csv'
[2025-03-30 22:20:43,954] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-03-30 22:20:44,020] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
