[2025-03-30 16:51:14,339] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: bigquery_to_gcs_using_python.query_and_upload_to_gcs manual__2025-03-30T16:51:11.779240+00:00 [queued]>
[2025-03-30 16:51:14,355] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: bigquery_to_gcs_using_python.query_and_upload_to_gcs manual__2025-03-30T16:51:11.779240+00:00 [queued]>
[2025-03-30 16:51:14,356] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 16:51:14,356] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 16:51:14,356] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 16:51:14,369] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): query_and_upload_to_gcs> on 2025-03-30 16:51:11.779240+00:00
[2025-03-30 16:51:14,376] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2025-03-30 16:51:14,381] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bigquery_to_gcs_using_python', 'query_and_upload_to_gcs', 'manual__2025-03-30T16:51:11.779240+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmptgra73gg', '--error-file', '/tmp/tmp6s77hnng']
[2025-03-30 16:51:14,385] {standard_task_runner.py:77} INFO - Job 2: Subtask query_and_upload_to_gcs
[2025-03-30 16:51:14,458] {logging_mixin.py:109} INFO - Running <TaskInstance: bigquery_to_gcs_using_python.query_and_upload_to_gcs manual__2025-03-30T16:51:11.779240+00:00 [running]> on host fde8a3caf967
[2025-03-30 16:51:14,523] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bigquery_to_gcs_using_python
AIRFLOW_CTX_TASK_ID=query_and_upload_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T16:51:11.779240+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T16:51:11.779240+00:00
[2025-03-30 16:51:14,526] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,526] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,526] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,526] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,526] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,527] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 16:51:14,528] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 25, in query_to_gcs
    client = bigquery.Client(project=project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 235, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 320, in __init__
    self, credentials=credentials, client_options=client_options, _http=_http
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 178, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File /.google/credentials/google_credentials.json was not found.
[2025-03-30 16:51:14,546] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=bigquery_to_gcs_using_python, task_id=query_and_upload_to_gcs, execution_date=20250330T165111, start_date=20250330T165114, end_date=20250330T165114
[2025-03-30 16:51:14,562] {standard_task_runner.py:92} ERROR - Failed to execute job 2 for task query_and_upload_to_gcs
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 25, in query_to_gcs
    client = bigquery.Client(project=project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 235, in __init__
    _http=_http,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 320, in __init__
    self, credentials=credentials, client_options=client_options, _http=_http
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/client.py", line 178, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 459, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
    "File {} was not found.".format(filename)
google.auth.exceptions.DefaultCredentialsError: File /.google/credentials/google_credentials.json was not found.
[2025-03-30 16:51:14,596] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-03-30 16:51:14,635] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
