[2025-03-30 19:53:51,384] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: bigquery_to_gcs_using_python_parquet_optimized.query_and_upload_to_gcs_parquet_2003 manual__2025-03-30T19:53:49.590144+00:00 [queued]>
[2025-03-30 19:53:51,402] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: bigquery_to_gcs_using_python_parquet_optimized.query_and_upload_to_gcs_parquet_2003 manual__2025-03-30T19:53:49.590144+00:00 [queued]>
[2025-03-30 19:53:51,402] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 19:53:51,403] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 19:53:51,403] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 19:53:51,422] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): query_and_upload_to_gcs_parquet_2003> on 2025-03-30 19:53:49.590144+00:00
[2025-03-30 19:53:51,440] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bigquery_to_gcs_using_python_parquet_optimized', 'query_and_upload_to_gcs_parquet_2003', 'manual__2025-03-30T19:53:49.590144+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmp3a814ng5', '--error-file', '/tmp/tmpma1mj2g3']
[2025-03-30 19:53:51,445] {standard_task_runner.py:77} INFO - Job 33: Subtask query_and_upload_to_gcs_parquet_2003
[2025-03-30 19:53:51,436] {standard_task_runner.py:52} INFO - Started process 7272 to run task
[2025-03-30 19:53:51,556] {logging_mixin.py:109} INFO - Running <TaskInstance: bigquery_to_gcs_using_python_parquet_optimized.query_and_upload_to_gcs_parquet_2003 manual__2025-03-30T19:53:49.590144+00:00 [running]> on host f5b8902f5cd8
[2025-03-30 19:53:51,635] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bigquery_to_gcs_using_python_parquet_optimized
AIRFLOW_CTX_TASK_ID=query_and_upload_to_gcs_parquet_2003
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T19:53:49.590144+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T19:53:49.590144+00:00
[2025-03-30 19:53:51,645] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,645] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,646] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,646] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,646] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,647] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,647] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,648] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,648] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,649] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,649] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:51,649] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-03-30 19:53:52,294] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 57, in query_to_gcs
    table = pa.table(rows, schema=SCHEMA)
  File "pyarrow/table.pxi", line 2214, in pyarrow.lib.table
  File "pyarrow/table.pxi", line 1596, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 587, in pyarrow.lib._sanitize_arrays
ValueError: Schema and number of arrays unequal
[2025-03-30 19:53:52,317] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=bigquery_to_gcs_using_python_parquet_optimized, task_id=query_and_upload_to_gcs_parquet_2003, execution_date=20250330T195349, start_date=20250330T195351, end_date=20250330T195352
[2025-03-30 19:53:52,337] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task query_and_upload_to_gcs_parquet_2003
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_to_gcs.py", line 57, in query_to_gcs
    table = pa.table(rows, schema=SCHEMA)
  File "pyarrow/table.pxi", line 2214, in pyarrow.lib.table
  File "pyarrow/table.pxi", line 1596, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 587, in pyarrow.lib._sanitize_arrays
ValueError: Schema and number of arrays unequal
[2025-03-30 19:53:52,360] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-03-30 19:53:52,411] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
