[2025-03-31 02:17:08,800] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T02:11:53.999497+00:00 [queued]>
[2025-03-31 02:17:08,826] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T02:11:53.999497+00:00 [queued]>
[2025-03-31 02:17:08,827] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-31 02:17:08,827] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-31 02:17:08,827] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-31 02:17:08,850] {taskinstance.py:1259} INFO - Executing <Task(DataprocSubmitJobOperator): submit_pyspark_job> on 2025-03-31 02:11:53.999497+00:00
[2025-03-31 02:17:08,866] {standard_task_runner.py:52} INFO - Started process 653 to run task
[2025-03-31 02:17:08,872] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'submit_pyspark_job', 'manual__2025-03-31T02:11:53.999497+00:00', '--job-id', '551', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmpnk87bmq5', '--error-file', '/tmp/tmp2fzd5rgj']
[2025-03-31 02:17:08,877] {standard_task_runner.py:77} INFO - Job 551: Subtask submit_pyspark_job
[2025-03-31 02:17:08,988] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T02:11:53.999497+00:00 [running]> on host 65c454f46b2f
[2025-03-31 02:17:09,101] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=submit_pyspark_job
AIRFLOW_CTX_EXECUTION_DATE=2025-03-31T02:11:53.999497+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-31T02:11:53.999497+00:00
[2025-03-31 02:17:09,102] {dataproc.py:1997} INFO - Submitting job
[2025-03-31 02:17:09,103] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-31 02:17:09,274] {dataproc.py:2009} INFO - Job 587291bc-8ae9-490e-8449-18c75f22c954 submitted successfully.
[2025-03-31 02:17:09,299] {dataproc.py:2022} INFO - Waiting for job 587291bc-8ae9-490e-8449-18c75f22c954 to complete
[2025-03-31 02:17:39,589] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2024, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 871, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "us-natality-455214"
  job_id: "587291bc-8ae9-490e-8449-18c75f22c954"
}
placement {
  cluster_name: "us-natality-cluster"
  cluster_uuid: "21e76a27-0656-4c6d-bfc7-e9e672f4f306"
}
pyspark_job {
  main_python_file_uri: "gs://us-natality-bucket/scripts/pyspark_to_bq.py"
}
status {
  state: ERROR
  details: "Job failed with message [TypeError: unsupported operand type(s) for +: \'NoneType\' and \'str\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/587291bc-8ae9-490e-8449-18c75f22c954?project=us-natality-455214&region=us-central1\ngcloud dataproc jobs wait \'587291bc-8ae9-490e-8449-18c75f22c954\' --region \'us-central1\' --project \'us-natality-455214\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/\ngs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/driveroutput.*"
  state_start_time {
    seconds: 1743387453
    nanos: 666588000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1743387429
    nanos: 254050000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1743387429
    nanos: 286843000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1743387429
    nanos: 724981000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/driveroutput"
job_uuid: "587291bc-8ae9-490e-8449-18c75f22c954"
done: true

[2025-03-31 02:17:39,598] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=natality_web_data_to_gcs, task_id=submit_pyspark_job, execution_date=20250331T021153, start_date=20250331T021708, end_date=20250331T021739
[2025-03-31 02:17:39,617] {standard_task_runner.py:92} ERROR - Failed to execute job 551 for task submit_pyspark_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2024, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 871, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "us-natality-455214"
  job_id: "587291bc-8ae9-490e-8449-18c75f22c954"
}
placement {
  cluster_name: "us-natality-cluster"
  cluster_uuid: "21e76a27-0656-4c6d-bfc7-e9e672f4f306"
}
pyspark_job {
  main_python_file_uri: "gs://us-natality-bucket/scripts/pyspark_to_bq.py"
}
status {
  state: ERROR
  details: "Job failed with message [TypeError: unsupported operand type(s) for +: \'NoneType\' and \'str\']. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/587291bc-8ae9-490e-8449-18c75f22c954?project=us-natality-455214&region=us-central1\ngcloud dataproc jobs wait \'587291bc-8ae9-490e-8449-18c75f22c954\' --region \'us-central1\' --project \'us-natality-455214\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/\ngs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/driveroutput.*"
  state_start_time {
    seconds: 1743387453
    nanos: 666588000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1743387429
    nanos: 254050000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1743387429
    nanos: 286843000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1743387429
    nanos: 724981000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/21e76a27-0656-4c6d-bfc7-e9e672f4f306/jobs/587291bc-8ae9-490e-8449-18c75f22c954/driveroutput"
job_uuid: "587291bc-8ae9-490e-8449-18c75f22c954"
done: true

[2025-03-31 02:17:39,641] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-03-31 02:17:39,709] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
